### ISSUE TITLE
Add Auth0

### ISSUE THREAD

**Issue by NominalTrajectory** [DUALSTACKS/cloudcredits.io#21]
### Which program would you like to see listed/updated on CloudCredits.io?

https://auth0.com/startups

**Comment by NominalTrajectory** [comment]
```yaml
provider_slug: "auth0"
title: "Auth0 for Startups"
meta_title: "Enjoy One Year Free"
intro: "Launch and grow your startup with Auth0's free one-year plan, featuring the benefits of the B2B professional plan. Confirm your eligibility and get started today."
description: "Auth0 offers a free one-year plan for startups, providing the benefits of their B2B Professional plan, including 100k Monthly Active Users, Enterprise MFA, and more."
status: "Active"
tags: ["startups", "free", "authentication"]
url: "https://auth0.com/"
value_type: "discount"
currency: "USD"
max_value: 0 # Free plan, so max_value is considered 0
community_notes: []
tiers:
  - name: "Startups"
    intro: "One year of Auth0, free for your startup"
    max_value: 0 # Free plan
    url: "https://auth0.com/"
    benefits:
      - "100k Monthly Active Users"
      - "Enterprise MFA"
      - "Unlimited Organizations (subject to system limitations)"
      - "Unlimited Admins (subject to system limitations)"
      - "Inbound SCIM"
      - "5 Enterprise Connections"
    benefits_level: 3
    duration: ["1 year"]
    eligibility:
      - "Venture-backed with less than $5M in funding"
      - "Less than $1M in annual recurring revenue"
      - "Less than two years from the date of incorporation"
    effort_level: 1
    steps_to_apply:
      - name: "Build"
        description: "Use the Auth0 Free Plan as you begin developing your product. Once you need more features, like Enterprise MFA, or additional Organizations, move onto the next step."
        action: "Sign up"
        action_url: "https://auth0.com/signup"
      - name: "Launch"
        description: "Apply for the Auth0 for Startups program, which includes everything in our B2B Professional plan, to help you launch your product."
        action: "Apply now"
        action_url: "https://auth0.com/"
      - name: "Grow"
        description: "Continue scaling your product with Auth0’s flexible plan options, including self-service and enterprise plans that can be customized for your needs."
        action: "Review pricing"
        action_url: "https://auth0.com/pricing"
faq:
  - question: "What is the Auth0 for Startups program?"
    answer: "A free one-year plan for startups, providing the benefits of the B2B Professional plan, including 100k Monthly Active Users, Enterprise MFA, and more."
  - question: "Who can apply to the program?"
    answer: "Startups that are venture-backed with less than $5M in funding, have less than $1M in annual recurring revenue, and are less than two years from the date of incorporation."
success_stories:
  - title: "Ardy Naghshineh, Founder and CEO"
    summary: "We used Auth0 from day one to be able to spend our limited time on innovating and creating new user experiences rather than building another user authentication system."
    link: "https://auth0.com/"
  - title: "Adar Arnon, Co-Founder and CTO"
    summary: "Something that’s very clear is that big customers really care about identity management and security."
    link: "https://auth0.com/"
  - title: "Low Lin-Hui, Co-Founder"
    summary: "Auth0 has allowed us to significantly enhance the performance of our login UX and streamline our user onboarding."
    link: "https://auth0.com/"
```
